// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aria2-srv/proto/aria2/aria2.proto

package go_micro_srv_aria2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type AddURIReq struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddURIReq) Reset()         { *m = AddURIReq{} }
func (m *AddURIReq) String() string { return proto.CompactTextString(m) }
func (*AddURIReq) ProtoMessage()    {}
func (*AddURIReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{1}
}

func (m *AddURIReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddURIReq.Unmarshal(m, b)
}
func (m *AddURIReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddURIReq.Marshal(b, m, deterministic)
}
func (m *AddURIReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddURIReq.Merge(m, src)
}
func (m *AddURIReq) XXX_Size() int {
	return xxx_messageInfo_AddURIReq.Size(m)
}
func (m *AddURIReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddURIReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddURIReq proto.InternalMessageInfo

func (m *AddURIReq) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type AddURIRsp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddURIRsp) Reset()         { *m = AddURIRsp{} }
func (m *AddURIRsp) String() string { return proto.CompactTextString(m) }
func (*AddURIRsp) ProtoMessage()    {}
func (*AddURIRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{2}
}

func (m *AddURIRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddURIRsp.Unmarshal(m, b)
}
func (m *AddURIRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddURIRsp.Marshal(b, m, deterministic)
}
func (m *AddURIRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddURIRsp.Merge(m, src)
}
func (m *AddURIRsp) XXX_Size() int {
	return xxx_messageInfo_AddURIRsp.Size(m)
}
func (m *AddURIRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddURIRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddURIRsp proto.InternalMessageInfo

func (m *AddURIRsp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *AddURIRsp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type RemoveReq struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReq) Reset()         { *m = RemoveReq{} }
func (m *RemoveReq) String() string { return proto.CompactTextString(m) }
func (*RemoveReq) ProtoMessage()    {}
func (*RemoveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{3}
}

func (m *RemoveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReq.Unmarshal(m, b)
}
func (m *RemoveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReq.Marshal(b, m, deterministic)
}
func (m *RemoveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReq.Merge(m, src)
}
func (m *RemoveReq) XXX_Size() int {
	return xxx_messageInfo_RemoveReq.Size(m)
}
func (m *RemoveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReq proto.InternalMessageInfo

func (m *RemoveReq) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type RemoveRsp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRsp) Reset()         { *m = RemoveRsp{} }
func (m *RemoveRsp) String() string { return proto.CompactTextString(m) }
func (*RemoveRsp) ProtoMessage()    {}
func (*RemoveRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{4}
}

func (m *RemoveRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRsp.Unmarshal(m, b)
}
func (m *RemoveRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRsp.Marshal(b, m, deterministic)
}
func (m *RemoveRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRsp.Merge(m, src)
}
func (m *RemoveRsp) XXX_Size() int {
	return xxx_messageInfo_RemoveRsp.Size(m)
}
func (m *RemoveRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRsp proto.InternalMessageInfo

func (m *RemoveRsp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *RemoveRsp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type PauseReq struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseReq) Reset()         { *m = PauseReq{} }
func (m *PauseReq) String() string { return proto.CompactTextString(m) }
func (*PauseReq) ProtoMessage()    {}
func (*PauseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{5}
}

func (m *PauseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseReq.Unmarshal(m, b)
}
func (m *PauseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseReq.Marshal(b, m, deterministic)
}
func (m *PauseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseReq.Merge(m, src)
}
func (m *PauseReq) XXX_Size() int {
	return xxx_messageInfo_PauseReq.Size(m)
}
func (m *PauseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseReq.DiscardUnknown(m)
}

var xxx_messageInfo_PauseReq proto.InternalMessageInfo

func (m *PauseReq) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type PauseRsp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseRsp) Reset()         { *m = PauseRsp{} }
func (m *PauseRsp) String() string { return proto.CompactTextString(m) }
func (*PauseRsp) ProtoMessage()    {}
func (*PauseRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{6}
}

func (m *PauseRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseRsp.Unmarshal(m, b)
}
func (m *PauseRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseRsp.Marshal(b, m, deterministic)
}
func (m *PauseRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseRsp.Merge(m, src)
}
func (m *PauseRsp) XXX_Size() int {
	return xxx_messageInfo_PauseRsp.Size(m)
}
func (m *PauseRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PauseRsp proto.InternalMessageInfo

func (m *PauseRsp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *PauseRsp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type TellStatusReq struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TellStatusReq) Reset()         { *m = TellStatusReq{} }
func (m *TellStatusReq) String() string { return proto.CompactTextString(m) }
func (*TellStatusReq) ProtoMessage()    {}
func (*TellStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{7}
}

func (m *TellStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TellStatusReq.Unmarshal(m, b)
}
func (m *TellStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TellStatusReq.Marshal(b, m, deterministic)
}
func (m *TellStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TellStatusReq.Merge(m, src)
}
func (m *TellStatusReq) XXX_Size() int {
	return xxx_messageInfo_TellStatusReq.Size(m)
}
func (m *TellStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TellStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_TellStatusReq proto.InternalMessageInfo

func (m *TellStatusReq) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *TellStatusReq) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type TellStatusRsp struct {
	Info                 *StatusInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Err                  *Error      `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TellStatusRsp) Reset()         { *m = TellStatusRsp{} }
func (m *TellStatusRsp) String() string { return proto.CompactTextString(m) }
func (*TellStatusRsp) ProtoMessage()    {}
func (*TellStatusRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{8}
}

func (m *TellStatusRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TellStatusRsp.Unmarshal(m, b)
}
func (m *TellStatusRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TellStatusRsp.Marshal(b, m, deterministic)
}
func (m *TellStatusRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TellStatusRsp.Merge(m, src)
}
func (m *TellStatusRsp) XXX_Size() int {
	return xxx_messageInfo_TellStatusRsp.Size(m)
}
func (m *TellStatusRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_TellStatusRsp.DiscardUnknown(m)
}

var xxx_messageInfo_TellStatusRsp proto.InternalMessageInfo

func (m *TellStatusRsp) GetInfo() *StatusInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *TellStatusRsp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StatusInfo struct {
	Gid                  string      `protobuf:"bytes,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
	Status               string      `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	TotalLength          string      `protobuf:"bytes,3,opt,name=TotalLength,proto3" json:"TotalLength,omitempty"`
	CompletedLength      string      `protobuf:"bytes,4,opt,name=CompletedLength,proto3" json:"CompletedLength,omitempty"`
	UploadLength         string      `protobuf:"bytes,5,opt,name=UploadLength,proto3" json:"UploadLength,omitempty"`
	BitField             string      `protobuf:"bytes,6,opt,name=BitField,proto3" json:"BitField,omitempty"`
	DownloadSpeed        string      `protobuf:"bytes,7,opt,name=DownloadSpeed,proto3" json:"DownloadSpeed,omitempty"`
	UploadSpeed          string      `protobuf:"bytes,8,opt,name=UploadSpeed,proto3" json:"UploadSpeed,omitempty"`
	InfoHash             string      `protobuf:"bytes,9,opt,name=InfoHash,proto3" json:"InfoHash,omitempty"`
	NumSeeders           string      `protobuf:"bytes,10,opt,name=NumSeeders,proto3" json:"NumSeeders,omitempty"`
	Connections          string      `protobuf:"bytes,11,opt,name=Connections,proto3" json:"Connections,omitempty"`
	ErrorCode            string      `protobuf:"bytes,12,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMessage         string      `protobuf:"bytes,13,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	FollowedBy           []string    `protobuf:"bytes,14,rep,name=FollowedBy,proto3" json:"FollowedBy,omitempty"`
	BelongsTo            string      `protobuf:"bytes,15,opt,name=BelongsTo,proto3" json:"BelongsTo,omitempty"`
	Dir                  string      `protobuf:"bytes,16,opt,name=Dir,proto3" json:"Dir,omitempty"`
	Files                []*FileInfo `protobuf:"bytes,17,rep,name=Files,proto3" json:"Files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StatusInfo) Reset()         { *m = StatusInfo{} }
func (m *StatusInfo) String() string { return proto.CompactTextString(m) }
func (*StatusInfo) ProtoMessage()    {}
func (*StatusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{9}
}

func (m *StatusInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusInfo.Unmarshal(m, b)
}
func (m *StatusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusInfo.Marshal(b, m, deterministic)
}
func (m *StatusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusInfo.Merge(m, src)
}
func (m *StatusInfo) XXX_Size() int {
	return xxx_messageInfo_StatusInfo.Size(m)
}
func (m *StatusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatusInfo proto.InternalMessageInfo

func (m *StatusInfo) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *StatusInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StatusInfo) GetTotalLength() string {
	if m != nil {
		return m.TotalLength
	}
	return ""
}

func (m *StatusInfo) GetCompletedLength() string {
	if m != nil {
		return m.CompletedLength
	}
	return ""
}

func (m *StatusInfo) GetUploadLength() string {
	if m != nil {
		return m.UploadLength
	}
	return ""
}

func (m *StatusInfo) GetBitField() string {
	if m != nil {
		return m.BitField
	}
	return ""
}

func (m *StatusInfo) GetDownloadSpeed() string {
	if m != nil {
		return m.DownloadSpeed
	}
	return ""
}

func (m *StatusInfo) GetUploadSpeed() string {
	if m != nil {
		return m.UploadSpeed
	}
	return ""
}

func (m *StatusInfo) GetInfoHash() string {
	if m != nil {
		return m.InfoHash
	}
	return ""
}

func (m *StatusInfo) GetNumSeeders() string {
	if m != nil {
		return m.NumSeeders
	}
	return ""
}

func (m *StatusInfo) GetConnections() string {
	if m != nil {
		return m.Connections
	}
	return ""
}

func (m *StatusInfo) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *StatusInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *StatusInfo) GetFollowedBy() []string {
	if m != nil {
		return m.FollowedBy
	}
	return nil
}

func (m *StatusInfo) GetBelongsTo() string {
	if m != nil {
		return m.BelongsTo
	}
	return ""
}

func (m *StatusInfo) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *StatusInfo) GetFiles() []*FileInfo {
	if m != nil {
		return m.Files
	}
	return nil
}

type FileInfo struct {
	Index                string     `protobuf:"bytes,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Path                 string     `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	Length               string     `protobuf:"bytes,3,opt,name=Length,proto3" json:"Length,omitempty"`
	CompletedLength      string     `protobuf:"bytes,4,opt,name=CompletedLength,proto3" json:"CompletedLength,omitempty"`
	Selected             string     `protobuf:"bytes,5,opt,name=Selected,proto3" json:"Selected,omitempty"`
	URIs                 []*URIInfo `protobuf:"bytes,6,rep,name=URIs,proto3" json:"URIs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{10}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *FileInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileInfo) GetLength() string {
	if m != nil {
		return m.Length
	}
	return ""
}

func (m *FileInfo) GetCompletedLength() string {
	if m != nil {
		return m.CompletedLength
	}
	return ""
}

func (m *FileInfo) GetSelected() string {
	if m != nil {
		return m.Selected
	}
	return ""
}

func (m *FileInfo) GetURIs() []*URIInfo {
	if m != nil {
		return m.URIs
	}
	return nil
}

type URIInfo struct {
	URI                  string   `protobuf:"bytes,1,opt,name=URI,proto3" json:"URI,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URIInfo) Reset()         { *m = URIInfo{} }
func (m *URIInfo) String() string { return proto.CompactTextString(m) }
func (*URIInfo) ProtoMessage()    {}
func (*URIInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{11}
}

func (m *URIInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URIInfo.Unmarshal(m, b)
}
func (m *URIInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URIInfo.Marshal(b, m, deterministic)
}
func (m *URIInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URIInfo.Merge(m, src)
}
func (m *URIInfo) XXX_Size() int {
	return xxx_messageInfo_URIInfo.Size(m)
}
func (m *URIInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_URIInfo.DiscardUnknown(m)
}

var xxx_messageInfo_URIInfo proto.InternalMessageInfo

func (m *URIInfo) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *URIInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "go.micro.srv.aria2.Error")
	proto.RegisterType((*AddURIReq)(nil), "go.micro.srv.aria2.AddURIReq")
	proto.RegisterType((*AddURIRsp)(nil), "go.micro.srv.aria2.AddURIRsp")
	proto.RegisterType((*RemoveReq)(nil), "go.micro.srv.aria2.RemoveReq")
	proto.RegisterType((*RemoveRsp)(nil), "go.micro.srv.aria2.RemoveRsp")
	proto.RegisterType((*PauseReq)(nil), "go.micro.srv.aria2.PauseReq")
	proto.RegisterType((*PauseRsp)(nil), "go.micro.srv.aria2.PauseRsp")
	proto.RegisterType((*TellStatusReq)(nil), "go.micro.srv.aria2.TellStatusReq")
	proto.RegisterType((*TellStatusRsp)(nil), "go.micro.srv.aria2.TellStatusRsp")
	proto.RegisterType((*StatusInfo)(nil), "go.micro.srv.aria2.StatusInfo")
	proto.RegisterType((*FileInfo)(nil), "go.micro.srv.aria2.FileInfo")
	proto.RegisterType((*URIInfo)(nil), "go.micro.srv.aria2.URIInfo")
}

func init() {
	proto.RegisterFile("aria2-srv/proto/aria2/aria2.proto", fileDescriptor_a3a1f0900da2471c)
}

var fileDescriptor_a3a1f0900da2471c = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0xfd, 0x42, 0x7e, 0x48, 0x26, 0xf0, 0xc1, 0xb7, 0xfa, 0x54, 0x6d, 0x53, 0x40, 0xc1, 0xea,
	0x45, 0xa4, 0xaa, 0x41, 0x32, 0xea, 0x03, 0xf0, 0x8f, 0xab, 0xb6, 0x42, 0x4e, 0xf2, 0x00, 0x6e,
	0x76, 0x08, 0xab, 0x3a, 0x5e, 0x77, 0xd7, 0x81, 0xf2, 0x52, 0xbd, 0xee, 0x7d, 0x5f, 0xac, 0xda,
	0x59, 0x3b, 0x3f, 0xad, 0xa1, 0x42, 0xdc, 0x20, 0xcf, 0x39, 0xc7, 0x73, 0x26, 0xbb, 0xc7, 0x03,
	0xec, 0x47, 0x5a, 0x46, 0xfe, 0x5b, 0xa3, 0x6f, 0x0f, 0x52, 0xad, 0x32, 0x75, 0x40, 0xb5, 0xfb,
	0xdb, 0x27, 0x84, 0xb1, 0x89, 0xea, 0x4f, 0xe5, 0x58, 0xab, 0xbe, 0xd1, 0xb7, 0x7d, 0x62, 0xbc,
	0x43, 0xa8, 0x9f, 0x69, 0xad, 0x34, 0x63, 0x50, 0x1b, 0x2b, 0x81, 0xbc, 0xd2, 0xad, 0xf4, 0xea,
	0x21, 0x3d, 0xb3, 0x17, 0xd0, 0x10, 0x98, 0x45, 0x32, 0xe6, 0x6b, 0xdd, 0x4a, 0xaf, 0x15, 0xe6,
	0x95, 0xb7, 0x0b, 0xad, 0x23, 0x21, 0x46, 0x61, 0x10, 0xe2, 0x57, 0xb6, 0x0d, 0xd5, 0x99, 0x96,
	0xf4, 0x5e, 0x2b, 0xb4, 0x8f, 0xde, 0xfb, 0x39, 0x6d, 0x52, 0x4b, 0x4f, 0xa4, 0x28, 0xe8, 0x89,
	0x14, 0xec, 0x0d, 0x54, 0x51, 0x6b, 0x6a, 0xd9, 0xf6, 0x5f, 0xf6, 0xff, 0x1c, 0xaa, 0x4f, 0x13,
	0x85, 0x56, 0x65, 0xad, 0x42, 0x9c, 0xaa, 0x5b, 0xcc, 0xad, 0x56, 0x7b, 0x59, 0xab, 0x9c, 0x7e,
	0xbe, 0xd5, 0x0e, 0x34, 0xaf, 0xa2, 0x99, 0x79, 0xc0, 0x29, 0x28, 0xd8, 0xe7, 0x1b, 0xbd, 0x83,
	0xcd, 0x21, 0xc6, 0xf1, 0x20, 0x8b, 0xb2, 0x99, 0x29, 0x75, 0xb3, 0xb7, 0xf1, 0x05, 0xef, 0x0d,
	0x5f, 0xeb, 0x56, 0x7b, 0xad, 0x90, 0x9e, 0xbd, 0x74, 0xe5, 0x35, 0x93, 0x32, 0x1f, 0x6a, 0x32,
	0xb9, 0x56, 0xf4, 0x5e, 0xdb, 0xdf, 0x2b, 0x73, 0x75, 0xe2, 0x20, 0xb9, 0x56, 0x21, 0x69, 0x9f,
	0x36, 0xe8, 0xf7, 0x1a, 0xc0, 0xa2, 0x83, 0x1d, 0xf3, 0x62, 0x31, 0xe6, 0x85, 0x14, 0x36, 0x20,
	0x8e, 0x2f, 0x02, 0xe2, 0x2a, 0xd6, 0x85, 0xf6, 0x50, 0x65, 0x51, 0xfc, 0x01, 0x93, 0x49, 0x76,
	0xc3, 0xab, 0x44, 0x2e, 0x43, 0xac, 0x07, 0x5b, 0x27, 0x6a, 0x9a, 0xc6, 0x98, 0xa1, 0xc8, 0x55,
	0x35, 0x52, 0xfd, 0x0e, 0x33, 0x0f, 0x36, 0x46, 0x69, 0xac, 0xa2, 0x42, 0x56, 0x27, 0xd9, 0x0a,
	0xc6, 0x3a, 0xd0, 0x3c, 0x96, 0xd9, 0xb9, 0xc4, 0x58, 0xf0, 0x06, 0xf1, 0xf3, 0x9a, 0xbd, 0x86,
	0xcd, 0x53, 0x75, 0x97, 0x58, 0xf5, 0x20, 0x45, 0x14, 0x7c, 0x9d, 0x04, 0xab, 0xa0, 0x9d, 0xd8,
	0x75, 0x74, 0x9a, 0xa6, 0x9b, 0x78, 0x09, 0xb2, 0x1e, 0xf6, 0x14, 0x2e, 0x23, 0x73, 0xc3, 0x5b,
	0xce, 0xa3, 0xa8, 0xd9, 0x1e, 0xc0, 0xa7, 0xd9, 0x74, 0x80, 0x28, 0x50, 0x1b, 0x0e, 0xc4, 0x2e,
	0x21, 0xb6, 0xfb, 0x89, 0x4a, 0x12, 0x1c, 0x67, 0x52, 0x25, 0x86, 0xb7, 0x5d, 0xf7, 0x25, 0x88,
	0xed, 0x40, 0x8b, 0x0e, 0xfe, 0xc4, 0x7e, 0x83, 0x1b, 0xc4, 0x2f, 0x00, 0x7b, 0x06, 0x54, 0x7c,
	0x44, 0x63, 0xa2, 0x09, 0xf2, 0x4d, 0x77, 0x06, 0xcb, 0x98, 0x9d, 0xe1, 0x5c, 0xc5, 0xb1, 0xba,
	0x43, 0x71, 0x7c, 0xcf, 0xff, 0xa5, 0xe0, 0x2c, 0x21, 0xd6, 0xe1, 0x18, 0x63, 0x95, 0x4c, 0xcc,
	0x50, 0xf1, 0x2d, 0xe7, 0x30, 0x07, 0xec, 0xdd, 0x9e, 0x4a, 0xcd, 0xb7, 0xdd, 0xdd, 0x9e, 0x4a,
	0xcd, 0x7c, 0xa8, 0x9f, 0xcb, 0x18, 0x0d, 0xff, 0xaf, 0x5b, 0xed, 0xb5, 0xfd, 0x9d, 0xb2, 0xac,
	0x58, 0x01, 0x85, 0xcb, 0x49, 0xbd, 0x9f, 0x15, 0x68, 0x16, 0x18, 0xfb, 0x1f, 0xea, 0x41, 0x22,
	0xf0, 0x5b, 0x1e, 0x18, 0x57, 0xd8, 0x64, 0x5f, 0x45, 0xd9, 0x4d, 0x1e, 0x18, 0x7a, 0xb6, 0x31,
	0x5a, 0x49, 0x4a, 0xe3, 0xc9, 0x21, 0xe9, 0x40, 0x73, 0x80, 0x31, 0x8e, 0x33, 0x14, 0x79, 0x40,
	0xe6, 0x35, 0x3b, 0x80, 0xda, 0x28, 0x0c, 0x0c, 0x6f, 0xd0, 0xef, 0x78, 0x55, 0xf6, 0x3b, 0x46,
	0x61, 0xe0, 0xbe, 0x11, 0x2b, 0xf4, 0x0e, 0x61, 0x3d, 0x07, 0xec, 0xb1, 0x8c, 0xc2, 0xa0, 0x88,
	0xfc, 0x28, 0x0c, 0x1e, 0x8a, 0xbc, 0xff, 0x63, 0x0d, 0xea, 0x47, 0xb6, 0x19, 0xbb, 0x84, 0x86,
	0x5b, 0x7f, 0x6c, 0xb7, 0xcc, 0x6b, 0xbe, 0x39, 0x3b, 0x8f, 0xd1, 0x26, 0xf5, 0xfe, 0xb1, 0x9d,
	0xdc, 0x76, 0x2b, 0xef, 0x34, 0x5f, 0x8c, 0x9d, 0xc7, 0x68, 0xea, 0x74, 0x06, 0x75, 0xda, 0x5e,
	0xac, 0xf4, 0x1a, 0x8b, 0xb5, 0xd7, 0x79, 0x84, 0xa5, 0x36, 0x43, 0x80, 0xc5, 0x0a, 0x62, 0xfb,
	0x65, 0xea, 0x95, 0xcd, 0xd6, 0xf9, 0x9b, 0xc4, 0x76, 0xfd, 0xdc, 0xa0, 0x7f, 0x4f, 0x87, 0xbf,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x83, 0xfa, 0x30, 0xd5, 0xc3, 0x06, 0x00, 0x00,
}
