// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aria2-srv/proto/aria2/aria2.proto

package aria2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type AddURIReq struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddURIReq) Reset()         { *m = AddURIReq{} }
func (m *AddURIReq) String() string { return proto.CompactTextString(m) }
func (*AddURIReq) ProtoMessage()    {}
func (*AddURIReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{1}
}

func (m *AddURIReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddURIReq.Unmarshal(m, b)
}
func (m *AddURIReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddURIReq.Marshal(b, m, deterministic)
}
func (m *AddURIReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddURIReq.Merge(m, src)
}
func (m *AddURIReq) XXX_Size() int {
	return xxx_messageInfo_AddURIReq.Size(m)
}
func (m *AddURIReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddURIReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddURIReq proto.InternalMessageInfo

func (m *AddURIReq) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type AddURIRsp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddURIRsp) Reset()         { *m = AddURIRsp{} }
func (m *AddURIRsp) String() string { return proto.CompactTextString(m) }
func (*AddURIRsp) ProtoMessage()    {}
func (*AddURIRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{2}
}

func (m *AddURIRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddURIRsp.Unmarshal(m, b)
}
func (m *AddURIRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddURIRsp.Marshal(b, m, deterministic)
}
func (m *AddURIRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddURIRsp.Merge(m, src)
}
func (m *AddURIRsp) XXX_Size() int {
	return xxx_messageInfo_AddURIRsp.Size(m)
}
func (m *AddURIRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddURIRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddURIRsp proto.InternalMessageInfo

func (m *AddURIRsp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *AddURIRsp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type RemoveReq struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReq) Reset()         { *m = RemoveReq{} }
func (m *RemoveReq) String() string { return proto.CompactTextString(m) }
func (*RemoveReq) ProtoMessage()    {}
func (*RemoveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{3}
}

func (m *RemoveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReq.Unmarshal(m, b)
}
func (m *RemoveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReq.Marshal(b, m, deterministic)
}
func (m *RemoveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReq.Merge(m, src)
}
func (m *RemoveReq) XXX_Size() int {
	return xxx_messageInfo_RemoveReq.Size(m)
}
func (m *RemoveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReq proto.InternalMessageInfo

func (m *RemoveReq) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type RemoveRsp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRsp) Reset()         { *m = RemoveRsp{} }
func (m *RemoveRsp) String() string { return proto.CompactTextString(m) }
func (*RemoveRsp) ProtoMessage()    {}
func (*RemoveRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{4}
}

func (m *RemoveRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRsp.Unmarshal(m, b)
}
func (m *RemoveRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRsp.Marshal(b, m, deterministic)
}
func (m *RemoveRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRsp.Merge(m, src)
}
func (m *RemoveRsp) XXX_Size() int {
	return xxx_messageInfo_RemoveRsp.Size(m)
}
func (m *RemoveRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRsp proto.InternalMessageInfo

func (m *RemoveRsp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *RemoveRsp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type PauseReq struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseReq) Reset()         { *m = PauseReq{} }
func (m *PauseReq) String() string { return proto.CompactTextString(m) }
func (*PauseReq) ProtoMessage()    {}
func (*PauseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{5}
}

func (m *PauseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseReq.Unmarshal(m, b)
}
func (m *PauseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseReq.Marshal(b, m, deterministic)
}
func (m *PauseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseReq.Merge(m, src)
}
func (m *PauseReq) XXX_Size() int {
	return xxx_messageInfo_PauseReq.Size(m)
}
func (m *PauseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseReq.DiscardUnknown(m)
}

var xxx_messageInfo_PauseReq proto.InternalMessageInfo

func (m *PauseReq) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type PauseRsp struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseRsp) Reset()         { *m = PauseRsp{} }
func (m *PauseRsp) String() string { return proto.CompactTextString(m) }
func (*PauseRsp) ProtoMessage()    {}
func (*PauseRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{6}
}

func (m *PauseRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseRsp.Unmarshal(m, b)
}
func (m *PauseRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseRsp.Marshal(b, m, deterministic)
}
func (m *PauseRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseRsp.Merge(m, src)
}
func (m *PauseRsp) XXX_Size() int {
	return xxx_messageInfo_PauseRsp.Size(m)
}
func (m *PauseRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PauseRsp proto.InternalMessageInfo

func (m *PauseRsp) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *PauseRsp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type TellStatusReq struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TellStatusReq) Reset()         { *m = TellStatusReq{} }
func (m *TellStatusReq) String() string { return proto.CompactTextString(m) }
func (*TellStatusReq) ProtoMessage()    {}
func (*TellStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{7}
}

func (m *TellStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TellStatusReq.Unmarshal(m, b)
}
func (m *TellStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TellStatusReq.Marshal(b, m, deterministic)
}
func (m *TellStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TellStatusReq.Merge(m, src)
}
func (m *TellStatusReq) XXX_Size() int {
	return xxx_messageInfo_TellStatusReq.Size(m)
}
func (m *TellStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TellStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_TellStatusReq proto.InternalMessageInfo

func (m *TellStatusReq) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *TellStatusReq) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type TellStatusRsp struct {
	Info                 *StatusInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Err                  *Error      `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TellStatusRsp) Reset()         { *m = TellStatusRsp{} }
func (m *TellStatusRsp) String() string { return proto.CompactTextString(m) }
func (*TellStatusRsp) ProtoMessage()    {}
func (*TellStatusRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{8}
}

func (m *TellStatusRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TellStatusRsp.Unmarshal(m, b)
}
func (m *TellStatusRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TellStatusRsp.Marshal(b, m, deterministic)
}
func (m *TellStatusRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TellStatusRsp.Merge(m, src)
}
func (m *TellStatusRsp) XXX_Size() int {
	return xxx_messageInfo_TellStatusRsp.Size(m)
}
func (m *TellStatusRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_TellStatusRsp.DiscardUnknown(m)
}

var xxx_messageInfo_TellStatusRsp proto.InternalMessageInfo

func (m *TellStatusRsp) GetInfo() *StatusInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *TellStatusRsp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StatusInfo struct {
	Gid                  string      `protobuf:"bytes,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
	Status               string      `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	TotalLength          string      `protobuf:"bytes,3,opt,name=TotalLength,proto3" json:"TotalLength,omitempty"`
	CompletedLength      string      `protobuf:"bytes,4,opt,name=CompletedLength,proto3" json:"CompletedLength,omitempty"`
	UploadLength         string      `protobuf:"bytes,5,opt,name=UploadLength,proto3" json:"UploadLength,omitempty"`
	BitField             string      `protobuf:"bytes,6,opt,name=BitField,proto3" json:"BitField,omitempty"`
	DownloadSpeed        string      `protobuf:"bytes,7,opt,name=DownloadSpeed,proto3" json:"DownloadSpeed,omitempty"`
	UploadSpeed          string      `protobuf:"bytes,8,opt,name=UploadSpeed,proto3" json:"UploadSpeed,omitempty"`
	InfoHash             string      `protobuf:"bytes,9,opt,name=InfoHash,proto3" json:"InfoHash,omitempty"`
	NumSeeders           string      `protobuf:"bytes,10,opt,name=NumSeeders,proto3" json:"NumSeeders,omitempty"`
	Seeder               string      `protobuf:"bytes,11,opt,name=Seeder,proto3" json:"Seeder,omitempty"`
	PieceLength          string      `protobuf:"bytes,12,opt,name=PieceLength,proto3" json:"PieceLength,omitempty"`
	NumPieces            string      `protobuf:"bytes,13,opt,name=NumPieces,proto3" json:"NumPieces,omitempty"`
	Connections          string      `protobuf:"bytes,14,opt,name=Connections,proto3" json:"Connections,omitempty"`
	ErrorCode            string      `protobuf:"bytes,15,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMessage         string      `protobuf:"bytes,16,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	FollowedBy           []string    `protobuf:"bytes,17,rep,name=FollowedBy,proto3" json:"FollowedBy,omitempty"`
	BelongsTo            string      `protobuf:"bytes,18,opt,name=BelongsTo,proto3" json:"BelongsTo,omitempty"`
	Dir                  string      `protobuf:"bytes,19,opt,name=Dir,proto3" json:"Dir,omitempty"`
	Files                []*FileInfo `protobuf:"bytes,20,rep,name=Files,proto3" json:"Files,omitempty"`
	BitTorrent           *BitTorrent `protobuf:"bytes,21,opt,name=BitTorrent,proto3" json:"BitTorrent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StatusInfo) Reset()         { *m = StatusInfo{} }
func (m *StatusInfo) String() string { return proto.CompactTextString(m) }
func (*StatusInfo) ProtoMessage()    {}
func (*StatusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{9}
}

func (m *StatusInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusInfo.Unmarshal(m, b)
}
func (m *StatusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusInfo.Marshal(b, m, deterministic)
}
func (m *StatusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusInfo.Merge(m, src)
}
func (m *StatusInfo) XXX_Size() int {
	return xxx_messageInfo_StatusInfo.Size(m)
}
func (m *StatusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatusInfo proto.InternalMessageInfo

func (m *StatusInfo) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *StatusInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StatusInfo) GetTotalLength() string {
	if m != nil {
		return m.TotalLength
	}
	return ""
}

func (m *StatusInfo) GetCompletedLength() string {
	if m != nil {
		return m.CompletedLength
	}
	return ""
}

func (m *StatusInfo) GetUploadLength() string {
	if m != nil {
		return m.UploadLength
	}
	return ""
}

func (m *StatusInfo) GetBitField() string {
	if m != nil {
		return m.BitField
	}
	return ""
}

func (m *StatusInfo) GetDownloadSpeed() string {
	if m != nil {
		return m.DownloadSpeed
	}
	return ""
}

func (m *StatusInfo) GetUploadSpeed() string {
	if m != nil {
		return m.UploadSpeed
	}
	return ""
}

func (m *StatusInfo) GetInfoHash() string {
	if m != nil {
		return m.InfoHash
	}
	return ""
}

func (m *StatusInfo) GetNumSeeders() string {
	if m != nil {
		return m.NumSeeders
	}
	return ""
}

func (m *StatusInfo) GetSeeder() string {
	if m != nil {
		return m.Seeder
	}
	return ""
}

func (m *StatusInfo) GetPieceLength() string {
	if m != nil {
		return m.PieceLength
	}
	return ""
}

func (m *StatusInfo) GetNumPieces() string {
	if m != nil {
		return m.NumPieces
	}
	return ""
}

func (m *StatusInfo) GetConnections() string {
	if m != nil {
		return m.Connections
	}
	return ""
}

func (m *StatusInfo) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *StatusInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *StatusInfo) GetFollowedBy() []string {
	if m != nil {
		return m.FollowedBy
	}
	return nil
}

func (m *StatusInfo) GetBelongsTo() string {
	if m != nil {
		return m.BelongsTo
	}
	return ""
}

func (m *StatusInfo) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *StatusInfo) GetFiles() []*FileInfo {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *StatusInfo) GetBitTorrent() *BitTorrent {
	if m != nil {
		return m.BitTorrent
	}
	return nil
}

type FileInfo struct {
	Index                string     `protobuf:"bytes,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Path                 string     `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	Length               string     `protobuf:"bytes,3,opt,name=Length,proto3" json:"Length,omitempty"`
	CompletedLength      string     `protobuf:"bytes,4,opt,name=CompletedLength,proto3" json:"CompletedLength,omitempty"`
	Selected             string     `protobuf:"bytes,5,opt,name=Selected,proto3" json:"Selected,omitempty"`
	URIs                 []*URIInfo `protobuf:"bytes,6,rep,name=URIs,proto3" json:"URIs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{10}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *FileInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileInfo) GetLength() string {
	if m != nil {
		return m.Length
	}
	return ""
}

func (m *FileInfo) GetCompletedLength() string {
	if m != nil {
		return m.CompletedLength
	}
	return ""
}

func (m *FileInfo) GetSelected() string {
	if m != nil {
		return m.Selected
	}
	return ""
}

func (m *FileInfo) GetURIs() []*URIInfo {
	if m != nil {
		return m.URIs
	}
	return nil
}

type URIInfo struct {
	URI                  string   `protobuf:"bytes,1,opt,name=URI,proto3" json:"URI,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URIInfo) Reset()         { *m = URIInfo{} }
func (m *URIInfo) String() string { return proto.CompactTextString(m) }
func (*URIInfo) ProtoMessage()    {}
func (*URIInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{11}
}

func (m *URIInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URIInfo.Unmarshal(m, b)
}
func (m *URIInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URIInfo.Marshal(b, m, deterministic)
}
func (m *URIInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URIInfo.Merge(m, src)
}
func (m *URIInfo) XXX_Size() int {
	return xxx_messageInfo_URIInfo.Size(m)
}
func (m *URIInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_URIInfo.DiscardUnknown(m)
}

var xxx_messageInfo_URIInfo proto.InternalMessageInfo

func (m *URIInfo) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *URIInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type BitTorrent struct {
	AnnounceList         []*BitTorrent_AnnounceListArr `protobuf:"bytes,1,rep,name=AnnounceList,proto3" json:"AnnounceList,omitempty"`
	Comment              string                        `protobuf:"bytes,2,opt,name=Comment,proto3" json:"Comment,omitempty"`
	CreationDate         int64                         `protobuf:"varint,3,opt,name=CreationDate,proto3" json:"CreationDate,omitempty"`
	Mode                 string                        `protobuf:"bytes,4,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Info                 *BitTorrent_Info              `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *BitTorrent) Reset()         { *m = BitTorrent{} }
func (m *BitTorrent) String() string { return proto.CompactTextString(m) }
func (*BitTorrent) ProtoMessage()    {}
func (*BitTorrent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{12}
}

func (m *BitTorrent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitTorrent.Unmarshal(m, b)
}
func (m *BitTorrent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitTorrent.Marshal(b, m, deterministic)
}
func (m *BitTorrent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitTorrent.Merge(m, src)
}
func (m *BitTorrent) XXX_Size() int {
	return xxx_messageInfo_BitTorrent.Size(m)
}
func (m *BitTorrent) XXX_DiscardUnknown() {
	xxx_messageInfo_BitTorrent.DiscardUnknown(m)
}

var xxx_messageInfo_BitTorrent proto.InternalMessageInfo

func (m *BitTorrent) GetAnnounceList() []*BitTorrent_AnnounceListArr {
	if m != nil {
		return m.AnnounceList
	}
	return nil
}

func (m *BitTorrent) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *BitTorrent) GetCreationDate() int64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

func (m *BitTorrent) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *BitTorrent) GetInfo() *BitTorrent_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type BitTorrent_AnnounceListArr struct {
	Elem                 []string `protobuf:"bytes,1,rep,name=elem,proto3" json:"elem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitTorrent_AnnounceListArr) Reset()         { *m = BitTorrent_AnnounceListArr{} }
func (m *BitTorrent_AnnounceListArr) String() string { return proto.CompactTextString(m) }
func (*BitTorrent_AnnounceListArr) ProtoMessage()    {}
func (*BitTorrent_AnnounceListArr) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{12, 0}
}

func (m *BitTorrent_AnnounceListArr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitTorrent_AnnounceListArr.Unmarshal(m, b)
}
func (m *BitTorrent_AnnounceListArr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitTorrent_AnnounceListArr.Marshal(b, m, deterministic)
}
func (m *BitTorrent_AnnounceListArr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitTorrent_AnnounceListArr.Merge(m, src)
}
func (m *BitTorrent_AnnounceListArr) XXX_Size() int {
	return xxx_messageInfo_BitTorrent_AnnounceListArr.Size(m)
}
func (m *BitTorrent_AnnounceListArr) XXX_DiscardUnknown() {
	xxx_messageInfo_BitTorrent_AnnounceListArr.DiscardUnknown(m)
}

var xxx_messageInfo_BitTorrent_AnnounceListArr proto.InternalMessageInfo

func (m *BitTorrent_AnnounceListArr) GetElem() []string {
	if m != nil {
		return m.Elem
	}
	return nil
}

type BitTorrent_Info struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitTorrent_Info) Reset()         { *m = BitTorrent_Info{} }
func (m *BitTorrent_Info) String() string { return proto.CompactTextString(m) }
func (*BitTorrent_Info) ProtoMessage()    {}
func (*BitTorrent_Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3a1f0900da2471c, []int{12, 1}
}

func (m *BitTorrent_Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitTorrent_Info.Unmarshal(m, b)
}
func (m *BitTorrent_Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitTorrent_Info.Marshal(b, m, deterministic)
}
func (m *BitTorrent_Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitTorrent_Info.Merge(m, src)
}
func (m *BitTorrent_Info) XXX_Size() int {
	return xxx_messageInfo_BitTorrent_Info.Size(m)
}
func (m *BitTorrent_Info) XXX_DiscardUnknown() {
	xxx_messageInfo_BitTorrent_Info.DiscardUnknown(m)
}

var xxx_messageInfo_BitTorrent_Info proto.InternalMessageInfo

func (m *BitTorrent_Info) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "aria2.Error")
	proto.RegisterType((*AddURIReq)(nil), "aria2.AddURIReq")
	proto.RegisterType((*AddURIRsp)(nil), "aria2.AddURIRsp")
	proto.RegisterType((*RemoveReq)(nil), "aria2.RemoveReq")
	proto.RegisterType((*RemoveRsp)(nil), "aria2.RemoveRsp")
	proto.RegisterType((*PauseReq)(nil), "aria2.PauseReq")
	proto.RegisterType((*PauseRsp)(nil), "aria2.PauseRsp")
	proto.RegisterType((*TellStatusReq)(nil), "aria2.TellStatusReq")
	proto.RegisterType((*TellStatusRsp)(nil), "aria2.TellStatusRsp")
	proto.RegisterType((*StatusInfo)(nil), "aria2.StatusInfo")
	proto.RegisterType((*FileInfo)(nil), "aria2.FileInfo")
	proto.RegisterType((*URIInfo)(nil), "aria2.URIInfo")
	proto.RegisterType((*BitTorrent)(nil), "aria2.BitTorrent")
	proto.RegisterType((*BitTorrent_AnnounceListArr)(nil), "aria2.BitTorrent.AnnounceListArr")
	proto.RegisterType((*BitTorrent_Info)(nil), "aria2.BitTorrent.Info")
}

func init() {
	proto.RegisterFile("aria2-srv/proto/aria2/aria2.proto", fileDescriptor_a3a1f0900da2471c)
}

var fileDescriptor_a3a1f0900da2471c = []byte{
	// 819 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x9e, 0x63, 0xcb, 0xb1, 0x8f, 0x93, 0x26, 0xe5, 0xb2, 0x82, 0x10, 0xba, 0xc2, 0x15, 0x16,
	0xc0, 0xd8, 0xb0, 0x14, 0x73, 0xb0, 0x9b, 0x61, 0xbb, 0x48, 0x9c, 0xa6, 0x33, 0xd0, 0x06, 0x01,
	0x13, 0xef, 0x5e, 0xb3, 0x4e, 0x1d, 0x62, 0xb2, 0xe8, 0x91, 0x72, 0xbb, 0xbe, 0xc7, 0x1e, 0x63,
	0xd7, 0x7b, 0x8e, 0x3d, 0xd2, 0x70, 0x0e, 0x29, 0x5b, 0x4a, 0x5b, 0x0c, 0xeb, 0x8d, 0xc0, 0xf3,
	0x7d, 0xe7, 0x4f, 0x87, 0x1f, 0x49, 0x78, 0x9a, 0x5a, 0x9d, 0x8e, 0xbf, 0x75, 0xf6, 0xcd, 0xb3,
	0x95, 0x35, 0xa5, 0x79, 0xc6, 0xb6, 0xff, 0x9e, 0x30, 0x22, 0x22, 0x36, 0x92, 0x53, 0x88, 0x9e,
	0x5b, 0x6b, 0xac, 0x10, 0xd0, 0x99, 0x9b, 0x0c, 0x65, 0x6b, 0xd8, 0x1a, 0x45, 0x8a, 0xd7, 0xe2,
	0x11, 0x74, 0x33, 0x2c, 0x53, 0x9d, 0xcb, 0x9d, 0x61, 0x6b, 0xd4, 0x57, 0xc1, 0x4a, 0xbe, 0x84,
	0xfe, 0x59, 0x96, 0xcd, 0xd4, 0x54, 0xe1, 0xef, 0xe2, 0x10, 0xda, 0x6b, 0xab, 0x39, 0xae, 0xaf,
	0x68, 0x99, 0xfc, 0xb4, 0xa1, 0xdd, 0x8a, 0xe8, 0x85, 0xce, 0x2a, 0x7a, 0xa1, 0x33, 0xf1, 0x04,
	0xda, 0x68, 0x2d, 0xa7, 0x1c, 0x8c, 0xf7, 0x4e, 0x7c, 0x53, 0xdc, 0x84, 0x22, 0x82, 0xb2, 0x2b,
	0x5c, 0x9a, 0x37, 0x18, 0xb2, 0x37, 0xc3, 0x29, 0x7b, 0xa0, 0x3f, 0x29, 0xfb, 0x63, 0xe8, 0x5d,
	0xa7, 0x6b, 0xf7, 0x91, 0xe4, 0x3f, 0x56, 0xec, 0x27, 0xe5, 0xfe, 0x1e, 0xf6, 0x6f, 0x31, 0xcf,
	0x6f, 0xca, 0xb4, 0x5c, 0xbb, 0x0f, 0x16, 0xa0, 0x31, 0xff, 0x86, 0xef, 0x9c, 0xdc, 0x19, 0xb6,
	0x47, 0x7d, 0xc5, 0xeb, 0xe4, 0x97, 0x46, 0x98, 0x5b, 0x89, 0x63, 0xe8, 0xe8, 0xe2, 0xb5, 0xe1,
	0xb8, 0xc1, 0xf8, 0x61, 0x28, 0xe4, 0xf9, 0x69, 0xf1, 0xda, 0x28, 0xa6, 0xff, 0xb3, 0x9d, 0xbf,
	0x22, 0x80, 0x6d, 0x10, 0x35, 0xf3, 0x62, 0xdb, 0xcc, 0x0b, 0x9d, 0xd1, 0xfe, 0x7a, 0xbe, 0xda,
	0x5f, 0x6f, 0x89, 0x21, 0x0c, 0x6e, 0x4d, 0x99, 0xe6, 0x2f, 0xb1, 0x58, 0x94, 0x77, 0xb2, 0xcd,
	0x64, 0x1d, 0x12, 0x23, 0x38, 0x98, 0x98, 0xe5, 0x2a, 0xc7, 0x12, 0xb3, 0xe0, 0xd5, 0x61, 0xaf,
	0xfb, 0xb0, 0x48, 0x60, 0x6f, 0xb6, 0xca, 0x4d, 0x5a, 0xb9, 0x45, 0xec, 0xd6, 0xc0, 0x44, 0x0c,
	0xbd, 0x73, 0x5d, 0x5e, 0x6a, 0xcc, 0x33, 0xd9, 0x65, 0x7e, 0x63, 0x8b, 0xaf, 0x60, 0xff, 0xc2,
	0xbc, 0x2d, 0xc8, 0xfb, 0x66, 0x85, 0x98, 0xc9, 0x5d, 0x76, 0x68, 0x82, 0xd4, 0xb1, 0xcf, 0xe8,
	0x7d, 0x7a, 0xbe, 0xe3, 0x1a, 0x44, 0x35, 0x68, 0x0a, 0x3f, 0xa7, 0xee, 0x4e, 0xf6, 0x7d, 0x8d,
	0xca, 0x16, 0x4f, 0x00, 0xae, 0xd6, 0xcb, 0x1b, 0xc4, 0x0c, 0xad, 0x93, 0xc0, 0x6c, 0x0d, 0xe1,
	0x39, 0xf1, 0x52, 0x0e, 0xc2, 0x9c, 0xd8, 0xa2, 0xaa, 0xd7, 0x1a, 0xe7, 0x18, 0x7e, 0x6d, 0xcf,
	0x57, 0xad, 0x41, 0xe2, 0x31, 0xf4, 0xaf, 0xd6, 0x4b, 0x46, 0x9c, 0xdc, 0x67, 0x7e, 0x0b, 0x50,
	0xfc, 0xc4, 0x14, 0x05, 0xce, 0x4b, 0x6d, 0x0a, 0x27, 0x1f, 0xf8, 0xf8, 0x1a, 0x44, 0xf1, 0xbc,
	0xa1, 0x13, 0x3a, 0x9a, 0x07, 0x3e, 0x7e, 0x03, 0xd0, 0x6c, 0xd9, 0x78, 0x85, 0xce, 0xa5, 0x0b,
	0x94, 0x87, 0x7e, 0xb6, 0x75, 0x8c, 0xfe, 0xed, 0xd2, 0xe4, 0xb9, 0x79, 0x8b, 0xd9, 0xf9, 0x3b,
	0xf9, 0x90, 0x65, 0x57, 0x43, 0xa8, 0xc2, 0x39, 0xe6, 0xa6, 0x58, 0xb8, 0x5b, 0x23, 0x85, 0xaf,
	0xb0, 0x01, 0x48, 0x33, 0x17, 0xda, 0xca, 0xcf, 0xbd, 0x66, 0x2e, 0xb4, 0x15, 0xc7, 0x10, 0x5d,
	0xea, 0x1c, 0x9d, 0x3c, 0x1a, 0xb6, 0x47, 0x83, 0xf1, 0x41, 0x90, 0x1d, 0x61, 0x2c, 0x4d, 0xcf,
	0x8a, 0xef, 0x00, 0xce, 0x75, 0x79, 0x6b, 0xac, 0xc5, 0xa2, 0x94, 0x5f, 0x34, 0x84, 0xbc, 0x25,
	0x54, 0xcd, 0x29, 0xf9, 0xbb, 0x05, 0xbd, 0x2a, 0x8d, 0x38, 0x82, 0x68, 0x5a, 0x64, 0xf8, 0x47,
	0x90, 0xab, 0x37, 0xe8, 0xf4, 0x5c, 0xa7, 0xe5, 0x5d, 0x90, 0x2b, 0xaf, 0x69, 0x73, 0x1a, 0x3a,
	0xed, 0xfe, 0x6f, 0x89, 0xc6, 0xd0, 0xbb, 0xc1, 0x1c, 0xe7, 0x25, 0x66, 0x41, 0x9e, 0x1b, 0x5b,
	0x24, 0xd0, 0x99, 0xa9, 0xa9, 0x93, 0x5d, 0xfe, 0xdb, 0x07, 0xe1, 0x0f, 0x66, 0x6a, 0xea, 0xcf,
	0x21, 0x71, 0xc9, 0x29, 0xec, 0x06, 0x80, 0xe6, 0x35, 0x53, 0xd3, 0xea, 0x8c, 0xcd, 0xd4, 0xf4,
	0x63, 0x67, 0x2c, 0xf9, 0x73, 0xa7, 0x3e, 0x21, 0xf1, 0x1c, 0xf6, 0xce, 0x8a, 0xc2, 0xac, 0x8b,
	0x39, 0xbe, 0xd4, 0xae, 0x94, 0x2d, 0xae, 0xf7, 0xf4, 0xbd, 0x89, 0x9d, 0xd4, 0xbd, 0xce, 0xac,
	0x55, 0x8d, 0x30, 0x21, 0x61, 0x77, 0x62, 0x96, 0x4b, 0x9a, 0xb9, 0x2f, 0x57, 0x99, 0xa4, 0x95,
	0x89, 0xc5, 0x94, 0x64, 0x75, 0x91, 0x96, 0xc8, 0xc3, 0x6a, 0xab, 0x06, 0x46, 0xe3, 0x7d, 0x45,
	0x42, 0xf3, 0x73, 0xe2, 0xb5, 0xf8, 0x3a, 0xdc, 0x45, 0x11, 0x6f, 0xe1, 0xa3, 0xf7, 0x1b, 0xda,
	0x5e, 0x48, 0xf1, 0x31, 0x1c, 0xdc, 0x6b, 0x8f, 0x52, 0x62, 0x8e, 0x4b, 0xfe, 0x9f, 0xbe, 0xe2,
	0x75, 0x1c, 0x43, 0x87, 0x87, 0x25, 0xa0, 0x73, 0x95, 0x2e, 0x31, 0x4c, 0x8b, 0xd7, 0xe3, 0x7f,
	0x5a, 0x10, 0x9d, 0x51, 0x09, 0x71, 0x02, 0x5d, 0xff, 0x8a, 0x88, 0xc3, 0x50, 0x74, 0xf3, 0xe6,
	0xc4, 0xf7, 0x10, 0xb7, 0x4a, 0x3e, 0x23, 0x7f, 0xff, 0x2e, 0x6c, 0xfc, 0x37, 0xaf, 0x48, 0x7c,
	0x0f, 0x61, 0xff, 0x6f, 0x20, 0xe2, 0xab, 0x5e, 0x54, 0x12, 0xae, 0x9e, 0x85, 0xb8, 0x09, 0xb0,
	0xf3, 0x0f, 0x00, 0xdb, 0x2b, 0x5a, 0x1c, 0x05, 0x87, 0xc6, 0x65, 0x1f, 0x7f, 0x00, 0xa5, 0xd8,
	0x5f, 0xbb, 0xfc, 0xe0, 0x9e, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x4d, 0x1e, 0x1f, 0x95,
	0x07, 0x00, 0x00,
}
